### ISSUE TITLE
s-tui doesn't seem to work on armhf

### ISSUE THREAD

**Issue by highvoltage** [amanusk/s-tui#102] opened 2018-12-02 08:26 UTC
### Step 1: Describe your environment

  * Debian on Olimex OLinuXino LIME2
  * s-tui version: 0.8.2
  * Installation method(pip/PPA/source code): Debian package
  
#### Observed Results:

Forwarded from Debian bug report [914194](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=914194):

I tried running s-tui on my Olimex OLinuXino LIME2 device, running
Debian armhf.

It failed with a stacktrace:

Traceback (most recent call last):
  File "/usr/bin/s-tui", line 11, in <module>
    load_entry_point('s-tui==0.8.2', 'console_scripts', 's-tui')()
  File "/usr/lib/python3/dist-packages/s_tui/s_tui.py", line 927, in main
    graph_controller = GraphController(args)
  File "/usr/lib/python3/dist-packages/s_tui/s_tui.py", line 728, in __init__
    self.view = GraphView(self)
  File "/usr/lib/python3/dist-packages/s_tui/s_tui.py", line 233, in __init__
    urwid.WidgetPlaceholder.__init__(self, self.main_window())
  File "/usr/lib/python3/dist-packages/s_tui/s_tui.py", line 552, in main_window
    self.controller.temp_thresh)
  File "/usr/lib/python3/dist-packages/s_tui/Sources/TemperatureSource.py", line 54, in __init__
    self.update()
  File "/usr/lib/python3/dist-packages/s_tui/Sources/TemperatureSource.py", line 146, in update
    update_func(sensor, 0)
  File "/usr/lib/python3/dist-packages/s_tui/Sources/TemperatureSource.py", line 93, in update_func
    Source.update(self)
  File "/usr/lib/python3/dist-packages/s_tui/Sources/Source.py", line 28, in update
    self.eval_hooks()
  File "/usr/lib/python3/dist-packages/s_tui/Sources/Source.py", line 68, in eval_hooks
    if self.get_edge_triggered():
  File "/usr/lib/python3/dist-packages/s_tui/Sources/TemperatureSource.py", line 190, in get_edge_triggered
    return self.last_temp > self.temp_thresh
TypeError: '>' not supported between instances of 'float' and 'NoneType'

#### Steps to reproduce:
1. Install a Debian armhf instance
2. apt install s-tui
3. s-tui

**Comment by amanusk** [comment] 2018-12-02 09:17
Hi,
Thanks for opening the issue, and for porting s-tui to Debian!
I believe the issue is supposed to be solved in the latest version (0.8.3),

**Comment by amanusk** [comment] 2018-12-27 07:22
Seems this fixes the bug. 
Closing.
Thanks @highvoltage

**Closed by amanusk** 2018-12-27 07:22 UTC
